# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import uuid_pb2 as uuid__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in uuid_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UUIDServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUUID = channel.unary_unary(
                '/pratice.UUIDService/GetUUID',
                request_serializer=uuid__pb2.UUIDRequest.SerializeToString,
                response_deserializer=uuid__pb2.UUIDResponse.FromString,
                _registered_method=True)


class UUIDServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUUID(self, request, context):
        """simple unary service method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UUIDServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUUID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUUID,
                    request_deserializer=uuid__pb2.UUIDRequest.FromString,
                    response_serializer=uuid__pb2.UUIDResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pratice.UUIDService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pratice.UUIDService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UUIDService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUUID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pratice.UUIDService/GetUUID',
            uuid__pb2.UUIDRequest.SerializeToString,
            uuid__pb2.UUIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
