# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: uuid.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'uuid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuuid.proto\x12\x07pratice\"F\n\x0bUUIDRequest\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x13\n\x0bvalueToHash\x18\x03 \x01(\t\"\x1c\n\x0cUUIDResponse\x12\x0c\n\x04uuid\x18\x01 \x01(\t2E\n\x0bUUIDService\x12\x36\n\x07GetUUID\x12\x14.pratice.UUIDRequest\x1a\x15.pratice.UUIDResponseB\x15Z\x13pratice/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uuid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023pratice/proto;proto'
  _globals['_UUIDREQUEST']._serialized_start=23
  _globals['_UUIDREQUEST']._serialized_end=93
  _globals['_UUIDRESPONSE']._serialized_start=95
  _globals['_UUIDRESPONSE']._serialized_end=123
  _globals['_UUIDSERVICE']._serialized_start=125
  _globals['_UUIDSERVICE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
