// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: uuid.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UUIDService_GetUUID_FullMethodName = "/pratice.UUIDService/GetUUID"
)

// UUIDServiceClient is the client API for UUIDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UUIDServiceClient interface {
	GetUUID(ctx context.Context, in *UUIDRequest, opts ...grpc.CallOption) (*UUIDResponse, error)
}

type uUIDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUUIDServiceClient(cc grpc.ClientConnInterface) UUIDServiceClient {
	return &uUIDServiceClient{cc}
}

func (c *uUIDServiceClient) GetUUID(ctx context.Context, in *UUIDRequest, opts ...grpc.CallOption) (*UUIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UUIDResponse)
	err := c.cc.Invoke(ctx, UUIDService_GetUUID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UUIDServiceServer is the server API for UUIDService service.
// All implementations must embed UnimplementedUUIDServiceServer
// for forward compatibility.
type UUIDServiceServer interface {
	GetUUID(context.Context, *UUIDRequest) (*UUIDResponse, error)
	mustEmbedUnimplementedUUIDServiceServer()
}

// UnimplementedUUIDServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUUIDServiceServer struct{}

func (UnimplementedUUIDServiceServer) GetUUID(context.Context, *UUIDRequest) (*UUIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUUID not implemented")
}
func (UnimplementedUUIDServiceServer) mustEmbedUnimplementedUUIDServiceServer() {}
func (UnimplementedUUIDServiceServer) testEmbeddedByValue()                     {}

// UnsafeUUIDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UUIDServiceServer will
// result in compilation errors.
type UnsafeUUIDServiceServer interface {
	mustEmbedUnimplementedUUIDServiceServer()
}

func RegisterUUIDServiceServer(s grpc.ServiceRegistrar, srv UUIDServiceServer) {
	// If the following call pancis, it indicates UnimplementedUUIDServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UUIDService_ServiceDesc, srv)
}

func _UUIDService_GetUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UUIDServiceServer).GetUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UUIDService_GetUUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UUIDServiceServer).GetUUID(ctx, req.(*UUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UUIDService_ServiceDesc is the grpc.ServiceDesc for UUIDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UUIDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pratice.UUIDService",
	HandlerType: (*UUIDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUUID",
			Handler:    _UUIDService_GetUUID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uuid.proto",
}
